### ISSUE TITLE
Error when trying to build

### ISSUE THREAD

**Issue by Gourave** [paysafegroup/paysafe_sdk_android#9]
This lib seems pretty outdated and unmaintained.

I tried to build the project and ran into a number of errors that I had to fix:
1. 403 error when trying to fetch `cardinalcommerceprod`
2. under `Sdk.kt` there is a reference to `BuildConfig.VERSION_NAME` that gave me an error. It should be updated.

I would suggest that Paysafe include the `.aar` file in this repo so users can just download that file instead of having to try and fix these issues above (and any others) so they can start using the repo. It makes life easier and takes 2 mins for each update. If you can, create a gradle plugin to make it even easier.

# If anyone is reading this and considering using this library, I highly recommend looking at other solutions

**Comment by bozhidarpaysafe** [comment]
Fixed.
